name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      dp_dir:
        description: 'deployment json directory (e.g. deployment/admin.json, deployment/patient.json)'
        required: true
        default: 'deployments/admin.json'
      cont_name:
        description: 'container name (e.g. admin, patient)'
        required: true
        default: 'admin'  
      img_name:
        description: 'Image name (e.g. admin:latest, patient)'
        required: true
        default: '376120733871.dkr.ecr.ap-south-1.amazonaws.com/dev-admin-repo:latest'         
      svc_name:
        description: 'svc name (e.g. admi-svc, patient-svc)'
        required: true
        default: 'admi-svc'        
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Render task definition with image 
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        
        with:
          task-definition: ${{ github.event.inputs.dp_dir }}
          container-name: ${{ github.event.inputs.cont_name }}
          image: ${{ github.event.inputs.img_name }} 

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: dev-ecs-cluster
          service: ${{ github.event.inputs.svc_name }}
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
